name: Build and Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js application
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fe:$GITHUB_SHA .
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fe:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy frontend \
          --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fe:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
